/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EMS__factory } from "./EMS__factory";
export { EMSManagement__factory } from "./EMSManagement__factory";
